# Content Based Recommendation

In [4]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
pd.set_option('display.expand_frame_repr', False)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Section I - TF-IDF Matrix


### Step #1
Read Data

In [5]:
df = pd.read_csv("datasets/the_movies_dataset/movies_metadata.csv", low_memory=False)

In [7]:
df.head()

   adult                              belongs_to_collection    budget                                             genres                              homepage     id    imdb_id original_language               original_title                                           overview popularity                       poster_path                               production_companies                               production_countries release_date      revenue  runtime                                   spoken_languages    status                                            tagline                        title  video  vote_average  vote_count
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...  http://toystory.disney.com/toy-story    862  tt0114709                en                    Toy Story  Led by Woody, Andy's toys live happily in his ...  21.946943  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg     [{'name': 'Pixar Animation Studios', 'id': 3}]  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30  373554033.0     81.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released                                                NaN                    Toy Story  False           7.7      5415.0
1  False                                                NaN  65000000  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...                                   NaN   8844  tt0113497                en                      Jumanji  When siblings Judy and Peter discover an encha...  17.015539  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg  [{'name': 'TriStar Pictures', 'id': 559}, {'na...  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-15  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released          Roll the dice and unleash the excitement!                      Jumanji  False           6.9      2413.0
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...                                   NaN  15602  tt0113228                en             Grumpier Old Men  A family wedding reignites the ancient feud be...    11.7129  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg  [{'name': 'Warner Bros.', 'id': 6194}, {'name'...  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22          0.0    101.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released  Still Yelling. Still Fighting. Still Ready for...             Grumpier Old Men  False           6.5        92.0
3  False                                                NaN  16000000  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...                                   NaN  31357  tt0114885                en            Waiting to Exhale  Cheated on, mistreated and stepped on, the wom...   3.859495  /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg  [{'name': 'Twentieth Century Fox Film Corporat...  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22   81452156.0    127.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released  Friends are the people who let you be yourself...            Waiting to Exhale  False           6.1        34.0
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0                     [{'id': 35, 'name': 'Comedy'}]                                   NaN  11862  tt0113041                en  Father of the Bride Part II  Just when George Banks has recovered from his ...   8.387519  /e64sOI48hQXyru7naBFyssKFxVd.jpg  [{'name': 'Sandollar Productions', 'id': 5842}...  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-02-10   76578911.0    106.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released  Just When His World Is Back To Normal... He's ...  Father of the Bride Part II  False           5.7       173.0

In [8]:
df.shape

(45466, 24)

In [9]:
df["overview"].head()

0    Led by Woody, Andy's toys live happily in his ...
1    When siblings Judy and Peter discover an encha...
2    A family wedding reignites the ancient feud be...
3    Cheated on, mistreated and stepped on, the wom...
4    Just when George Banks has recovered from his ...
Name: overview, dtype: object

### Step #2
TF-IDF Matrix

In [10]:
tfidf = TfidfVectorizer(stop_words="english")

In [11]:
df['overview'] = df['overview'].fillna('')

In [12]:
tfidf_matrix = tfidf.fit_transform(df['overview'])

In [13]:
tfidf_matrix.shape

(45466, 75827)

In [14]:
df['title'].shape

(45466,)

In [15]:
tfidf.get_feature_names()

/opt/homebrew/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['00',
 '000',
 '000km',
 '000th',
 '001',
 '006',
 '007',
 '008',
 '009',
 '0093',
 '01',
 '0123',
 '02',
 '03',
 '04',
 '042',
 '05',
 '05pm',
 '06',
 '07',
 '077',
 '07am',
 '08',
 '088',
 '09',
 '10',
 '100',
 '1000',
 '10000',
 '1000s',
 '1000th',
 '1001',
 '100th',
 '101',
 '101st',
 '103',
 '103rd',
 '104',
 '105',
 '1066',
 '108',
 '1080s',
 '108th',
 '109',
 '10b',
 '10crores',
 '10mn',
 '10th',
 '10x',
 '11',
 '110',
 '1100',
 '111',
 '112',
 '1138',
 '114',
 '115',
 '117',
 '117a',
 '118',
 '1183',
 '119',
 '11s',
 '11th',
 '12',
 '120',
 '1200',
 '1200s',
 '1206',
 '1215',
 '1218',
 '1227',
 '125',
 '1250',
 '125th',
 '1263',
 '129',
 '12th',
 '13',
 '130',
 '1300',
 '1300s',
 '1302',
 '1303',
 '133',
 '134',
 '1344',
 '1348',
 '1349',
 '138',
 '13anos',
 '13b',
 '13s',
 '13th',
 '14',
 '140',
 '1400',
 '1408',
 '1413',
 '142',
 '1429',
 '143',
 '144',
 '145',
 '1458',
 '146',
 '1463',
 '1466',
 '1472',
 '1475',
 '148',
 '1482',
 '1483',
 '1492',
 '14pm',
 '14th',
 '15',
 '150',
 '1500',
 '150000',
 '1500s',
 '1509',
 '150th',
 '1518',
 '1520s',
 '1526',
 '1528',
 '1536',
 '1537',
 '1543',
 '1547',
 '1548',
 '155',
 '1557',
 '1560',
 '1561',
 '1562',
 '1564',
 '1570',
 '1572',
 '1575',
 '1582',
 '1587',
 '1588',
 '1590',
 '1592',
 '1593',
 '1594',
 '1595',
 '1597',
 '1598',
 '1599',
 '15th',
 '15yrs',
 '15½',
 '16',
 '160',
 '1600',
 '1600s',
 '1600th',
 '1601',
 '1606',
 '161',
 '1610',
 '1612',
 '1614',
 '1615',
 '1616',
 '1625',
 '1626',
 '1630s',
 '1637',
 '1639',
 '164',
 '1640s',
 '1642',
 '1644',
 '1648',
 '1649',
 '165',
 '1651',
 '1653',
 '1654',
 '1656',
 '1666',
 '1669',
 '1671',
 '1678',
 '168',
 '1681',
 '1683',
 '1684',
 '1689',
 '168th',
 '1691',
 '1692',
 '1695',
 '1699',
 '16mm',
 '16th',
 '16yo',
 '17',
 '170',
 '1700',
 '1700s',
 '1701',
 '1710',
 '1715',
 '1716',
 '1724',
 '174',
 '1740',
 '1745',
 '1746',
 '1748',
 '175',
 '1757',
 '1760',
 '1760s',
 '1776',
 '1777',
 '1783',
 '1786',
 '1787',
 '1789',
 '1790s',
 '1791',
 '1792',
 '1793',
 '1794',
 '1797',
 '17months',
 '17th',
 '18',
 '180',
 '1800',
 '1800s',
 '1804',
 '1805',
 '1808',
 '1809',
 '180km',
 '180sm',
 '181',
 '1810',
 '1810s',
 '1811',
 '1812',
 '1813',
 '1814',
 '1815',
 '1816',
 '1817',
 '1818',
 '1819',
 '182',
 '1820',
 '1820s',
 '1823',
 '1824',
 '1825',
 '1826',
 '1828',
 '1830',
 '1830s',
 '1831',
 '1835',
 '1836',
 '1838',
 '1839',
 '184',
 '1840',
 '1840s',
 '1841',
 '1842',
 '1843',
 '1845',
 '1846',
 '1847',
 '1848',
 '1849',
 '185',
 '1850',
 '1850s',
 '1851',
 '1852',
 '1853',
 '1854',
 '1856',
 '1857',
 '1858',
 '1859',
 '186',
 '1860',
 '1860s',
 '1861',
 '1862',
 '1863',
 '1864',
 '1865',
 '1866',
 '1867',
 '1868',
 '1869',
 '1870',
 '1870s',
 '1871',
 '1873',
 '1874',
 '1875',
 '1876',
 '1877',
 '1878',
 '1879',
 '1880',
 '1880s',
 '1881',
 '1882',
 '1883',
 '1884',
 '1885',
 '1886',
 '1887',
 '1888',
 '1889',
 '1890',
 '1890s',
 '1891',
 '1892',
 '1893',
 '1894',
 '1895',
 '1896',
 '1897',
 '1898',
 '1899',
 '18th',
 '19',
 '190',
 '1900',
 '1900s',
 '1901',
 '1902',
 '1903',
 '1904',
 '1905',
 '1906',
 '1907',
 '1908',
 '1909',
 '191',
 '1910',
 '1910s',
 '1911',
 '1912',
 '1913',
 '1914',
 '1915',
 '1916',
 '1917',
 '1918',
 '1919',
 '192',
 '1920',
 '1920s',
 '1921',
 '1922',
 '1923',
 '1924',
 '1925',
 '1926',
 '1927',
 '1928',
 '1929',
 '1930',
 '1930s',
 '1931',
 '1932',
 '1933',
 '1934',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1940s',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1946',
 '1947',
 '1948',
 '1949',
 '1950',
 '1950s',
 '1951',
 '1952',
 '1953',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1960s',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1980th',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1990s',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19th',
 '19yo',
 '1felco',
 '1st',
 '20',
 '200',
 '2000',
 '20000',
 '2000ad',
 '2000s',
 '2000th',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2010fred',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2024',
 '2025',
 '2027',
 '2028',
 '2029',
 '2030',
 '2031',
 '2032',
 '2033',
 '2034',
 '2035',
 '2036',
 '2037',
 '2038',
 '2039',
 '2040',
 '2041',
 '2043',
 '2045',
 '2046',
 '2047',
 '2049',
 '2050',
 '2052',
 '2054',
 '2055',
 '2057',
 '2058',
 '2067',
 '2071',
 '2073',
 '2074',
 '2077',
 '2078',
 '208',
 '2081',
 '2084',
 '2087',
 '2092',
 '2095',
 '2096',
 '20s',
 '20something',
 '20th',
 '20xx',
 '21',
 '2100',
 '211',
 '2116',
 '212th',
 '213',
 '2150',
 '2159',
 '2163',
 '2167',
 '2199',
 '21rst',
 '21st',
 '22',
 '220',
 '2204',
 '221b',
 '223',
 '224',
 '2247',
 '2257',
 '226',
 '2267',
 '227',
 '229',
 '22nd',
 '23',
 '230',
 '2300',
 '2306',
 '2314',
 '234',
 '235',
 '236',
 '23rd',
 '24',
 '240',
 '2400',
 '242',
 '2455',
 '247',
 '2470',
 '248',
 '2491',
 '24h',
 '24th',
 '24yo',
 '25',
 '250',
 '2500',
 '25000',
 '2505',
 '2509',
 '250cc',
 '250th',
 '25143',
 '252',
 '2525',
 '257',
 '2577',
 '25k',
 '25th',
 '26',
 '260',
 '2600',
 '26000',
 '26th',
 '27',
 '2700',
 '2707',
 '2710',
 '276',
 '2784',
 '27th',
 '28',
 '280',
 '2808a',
 '280z',
 '286',
 '28th',
 '29',
 '2961',
 '29th',
 '2channel',
 '2d',
 '2ldk',
 '2m',
 '2manydj',
 '2nd',
 '2pac',
 '30',
 '300',
 '3000',
 '30000',
 '300000',
 '301',
 '302',
 '303',
 '305',
 '308th',
 '309',
 '30s',
 '30th',
 '31',
 '310lb',
 '3127',
 '316th',
 '318',
 '31st',
 '32',
 '320',
 '327',
 '33',
 '330',
 '3313',
 '332',
 '34',
 '341',
 '344m',
 '345',
 '346',
 '35',
 '350',
 '350lbs',
 '356',
 '359',
 '35mm',
 '35th',
 '36',
 '360',
 '365',
 '36th',
 '37',
 '370',
 '371',
 '375',
 '37th',
 '38',
 '383',
 '38th',
 '39',
 '396',
 '39th',
 '3a',
 '3am',
 '3d',
 '3dd',
 '3km',
 '3pm',
 '3po',
 '3rd',
 '3v3',
 '3½',
 '40',
 '400',
 '4000',
 '40000',
 '405',
 '407',
 '40s',
 '40ste',
 '40th',
 '41',
 '410',
 '413lbs',
 '41c',
 '41st',
 '42',
 '420',
 '422',
 '422nd',
 '427',
 '429',
 '43',
 '430',
 '436',
 '43rd',
 '44',
 '440',
 '442nd',
 '444th',
 '45',
 '450',
 '45365',
 '45s',
 '45th',
 '46',
 '465',
 '47',
 '47s',
 '47th',
 '48',
 '480',
 '485',
 '48hr',
 '48th',
 '49',
 '497',
 '49th',
 '4am',
 '4bia',
 '4chan',
 '4eb',
 '4ever',
 '4f',
 '4k',
 '4kids',
 '4million',
 '4th',
 '50',
 '500',
 '5000',
 '500th',
 '501',
 '501st',
 '506',
 '509th',
 '50enne',
 '50s',
 '50th',
 '51',
 '515',
 '5150',
 '51st',
 '52',
 '5200',
 '522',
 '52min',
 '52nd',
 '53',
 '530',
 '5307th',
 '533',
 '536',
 '54',
 '54th',
 '55',
 '56',
 '56pm',
 '56th',
 '57',
 '57th',
 '58',
 '59',
 '5am',
 '5m',
 '5th',
 '60',
 '600',
 '6000',
 '605',
 '60s',
 '60th',
 '61',
 '612',
 '617',
 '62',
 '625',
 '63',
 '633',
 '638',
 '64',
 '643',
 '65',
 '658',
 '65k',
 '65th',
 '66',
 '663',
 '666',
 '66th',
 '67',
 '670',
 '68',
 '68th',
 '69',
 '6am',
 '6b',
 '6m',
 '6th',
 '6wing',
 '70',
 '700',
 '701',
 '707',
 '70mm',
 '70s',
 '70th',
 '71',
 '71099',
 '7117',
 '72',
 '725',
 '73',
 '731',
 '74',
 '740',
 '743',
 '747',
 '74th',
 '75',
 '750',
 '7500',
 '751',
 '757',
 '75th',
 '76',
 '76ers',
 '76th',
 '77',
 '77th',
 '78',
 '79',
 '7days',
 '7pm',
 '7th',
 '80',
 '800',
 '8000',
 '800m',
 '808',
 '80s',
 '80th',
 '81',
 '82',
 '825',
 '83',
 '83rd',
 '84',
 '85',
 '850',
 '85million',
 '85th',
 '86',
 '87',
 '88',
 '880',
 '88888',
 '89',
 '8km',
 '8m',
 '8mm',
 '8pm',
 '8th',
 '8x10',
 '8½',
 '90',
 '900',
 '9000',
 '900lb',
 '90210',
 '907',
 '90s',
 '90th',
 '91',
 '911',
 '91st',
 '92',
 '922',
 '929',
 '92nd',
 '93',
 '937',
 '94',
 '9413',
 '95',
 '95er',
 '96',
 '964',
 '97',
 '976',
 '977',
 '98',
 '99',
 '999',
 '9mm',
 '9pm',
 '9th',
 '9to5',
 '_stakeout_',
 '_wizard',
 'a2',
 'a300',
 'aa',
 'aaa',
 'aaaron',
 'aab',
 'aachan',
 'aachi',
 'aackerlund',
 'aadhavan',
 'aadhi',
 'aadland',
 'aaicha',
 'aakash',
 'aake',
 'aalavandhan',
 'aalst',
 'aaltonen',
 'aames',
 'aamir',
 'aan',
 'aanandam',
 'aang',
 'aangehouden',
 'aanmodderfakker',
 'aapeli',
 'aarakshan',
 'aarchi',
 'aarne',
 'aarno',
 'aaron',
 'aarons',
 'aarp',
 'aart',
 'aarti',
 'aarya',
 'aarón',
 'aasen',
 'aashirvad',
 'aashish',
 'aasia',
 'aati',
 'aatish',
 'ab',
 'aba',
 'ababa',
 'abacco',
 'aback',
 'abacus',
 'abaddon',
 'abagnale',
 'abahachi',
 'abalaba',
 'aballay',
 'abalone',
 'abandon',
 'abandond',
 'abandoned',
 'abandoning',
 'abandonment',
 'abandons',
 'abar',
 'abard',
 'abargil',
 'abas',
 'abatcha',
 'abates',
 'abati',
 'abba',
 'abbaji',
 'abbas',
 'abbaseya',
 'abbasi',
 'abbass',
 'abbe',
 'abberline',
 'abbes',
 'abbess',
 'abbey',
 'abbia',
 'abbie',
 'abbot',
 'abbott',
 'abby',
 'abbé',
 'abc',
 'abcs',
 'abdallah',
 ...]

In [16]:
tfidf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Section II - Cosine Similarity Matrix

In [18]:
cosine_sim = cosine_similarity(tfidf_matrix,
                               tfidf_matrix)

In [19]:
cosine_sim.shape

(45466, 45466)

In [20]:
cosine_sim[1]

array([0.01504121, 1.        , 0.04681953, ..., 0.        , 0.02198641,
       0.00929411])

# Section III - Making Recommendations Based on Similarities

In [21]:
indices = pd.Series(df.index, index=df['title'])

indices.index.value_counts()

Cinderella              11
Hamlet                   9
Alice in Wonderland      9
Beauty and the Beast     8
Les Misérables           8
                        ..
Cluny Brown              1
Babies                   1
The Green Room           1
Captain Conan            1
Queerama                 1
Name: title, Length: 42277, dtype: int64

In [22]:
indices = indices[~indices.index.duplicated(keep='last')]

In [23]:
indices["Cinderella"]

45406

In [24]:
indices["Sherlock Holmes"]

35116

In [25]:
movie_index = indices["Sherlock Holmes"]

In [26]:
cosine_sim[movie_index]

array([0.        , 0.00392837, 0.00476764, ..., 0.        , 0.0067919 ,
       0.        ])

In [27]:
similarity_scores = pd.DataFrame(cosine_sim[movie_index],
                                 columns=["score"])

In [28]:
movie_indices = similarity_scores.sort_values("score", ascending=False)[1:11].index

In [29]:
df['title'].iloc[movie_indices]

34737    Приключения Шерлока Холмса и доктора Ватсона: ...
14821                                    The Royal Scandal
34750    The Adventures of Sherlock Holmes and Doctor W...
9743                           The Seven-Per-Cent Solution
4434                                        Without a Clue
29706                       How Sherlock Changed the World
18258                   Sherlock Holmes: A Game of Shadows
24665     The Sign of Four: Sherlock Holmes' Greatest Case
6432                   The Private Life of Sherlock Holmes
29154                          Sherlock Holmes in New York
Name: title, dtype: object

# Section IV - Project Script

In [31]:
def content_based_recommender(title, cosine_sim, dataframe):
    # index'leri olusturma
    indices = pd.Series(dataframe.index, index=dataframe['title'])
    indices = indices[~indices.index.duplicated(keep='last')]
    # title'ın index'ini yakalama
    movie_index = indices[title]
    # title'a gore benzerlik skorlarını hesapalama
    similarity_scores = pd.DataFrame(cosine_sim[movie_index], columns=["score"])
    # kendisi haric ilk 10 filmi getirme
    movie_indices = similarity_scores.sort_values("score", ascending=False)[1:11].index
    return dataframe['title'].iloc[movie_indices]

In [32]:
content_based_recommender("Sherlock Holmes", cosine_sim, df)

34737    Приключения Шерлока Холмса и доктора Ватсона: ...
14821                                    The Royal Scandal
34750    The Adventures of Sherlock Holmes and Doctor W...
9743                           The Seven-Per-Cent Solution
4434                                        Without a Clue
29706                       How Sherlock Changed the World
18258                   Sherlock Holmes: A Game of Shadows
24665     The Sign of Four: Sherlock Holmes' Greatest Case
6432                   The Private Life of Sherlock Holmes
29154                          Sherlock Holmes in New York
Name: title, dtype: object

In [33]:
content_based_recommender("The Matrix", cosine_sim, df)

44161                        A Detective Story
44167                              Kid's Story
44163                             World Record
33854                                Algorithm
167                                    Hackers
20707    Underground: The Julian Assange Story
6515                                  Commando
24202                                 Who Am I
22085                           Berlin Express
9159                                  Takedown
Name: title, dtype: object

In [34]:
content_based_recommender("The Godfather", cosine_sim, df)

1178               The Godfather: Part II
44030    The Godfather Trilogy: 1972-1990
1914              The Godfather: Part III
23126                          Blood Ties
11297                    Household Saints
34717                   Start Liquidation
10821                            Election
38030            A Mother Should Be Loved
17729                   Short Sharp Shock
26293                  Beck 28 - Familjen
Name: title, dtype: object

In [35]:
content_based_recommender('The Dark Knight Rises', cosine_sim, df)

12481                                      The Dark Knight
150                                         Batman Forever
1328                                        Batman Returns
15511                           Batman: Under the Red Hood
585                                                 Batman
21194    Batman Unmasked: The Psychology of the Dark Kn...
9230                    Batman Beyond: Return of the Joker
18035                                     Batman: Year One
19792              Batman: The Dark Knight Returns, Part 1
3095                          Batman: Mask of the Phantasm
Name: title, dtype: object

In [36]:
def calculate_cosine_sim(dataframe):
    tfidf = TfidfVectorizer(stop_words='english')
    dataframe['overview'] = dataframe['overview'].fillna('')
    tfidf_matrix = tfidf.fit_transform(dataframe['overview'])
    cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
    return cosine_sim

In [37]:
cosine_sim = calculate_cosine_sim(df)

In [38]:
content_based_recommender('The Dark Knight Rises', cosine_sim, df)

12481                                      The Dark Knight
150                                         Batman Forever
1328                                        Batman Returns
15511                           Batman: Under the Red Hood
585                                                 Batman
21194    Batman Unmasked: The Psychology of the Dark Kn...
9230                    Batman Beyond: Return of the Joker
18035                                     Batman: Year One
19792              Batman: The Dark Knight Returns, Part 1
3095                          Batman: Mask of the Phantasm
Name: title, dtype: object